### ISSUE TITLE
Counter being case sensitive

### ISSUE THREAD

**Issue by werunom** [RambIT-nl/highlight-counter#4]
Recently I observed that the highlighter counter has become case sensitive. See below

![highlight counter](https://user-images.githubusercontent.com/24664855/63274963-58bf0800-c2be-11e9-874b-17ddf61e17e9.gif)

Is this expected? Because, I do not want case sensitive counter. Probably ability to toggle or control that at the settings.json would be helpful.

Thanks!

**Comment by ramon-nl** [comment]
I have released a new version of the extension with the option to enable case sensitivity (disabled by default).
